# Линейная алгебра (Начало)
Мы будем использовать модули:
Numpy: https://numpy.org/doc/ 
SciPy: https://docs.scipy.org/doc/scipy/reference/ - более предпочтительна для задач линейной алгебры

In [2]:
import numpy as np

# Создание массивов

A = np.array([[1, 2., 3],[4, 5, 6]]) # Матрица 2х3
A

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
mylist = [1, 5., 'Hello']
mylist

[1, 5.0, 'Hello']

In [4]:
B = np.array([1, 5, 3], dtype= float)
B

array([1., 5., 3.])

In [6]:
C = np.array([1., 5, 3])
C

array([1., 5., 3.])

In [7]:
# Доступ к элементам по индексу, начиная с 0
C[1]

5.0

In [10]:
# изменение элементов
C[1] += 1
C

array([1., 8., 3.])

In [11]:
A[1,1]

5

In [12]:
A[1][1]

5

In [13]:
A[1] # 2-я строка

array([4, 5, 6])

In [17]:
A[:, 1]  # 2-й столбец

array([2, 5])

In [20]:
# Размерность массива
A.ndim

2

In [21]:
# Форма массива
A.shape

(2, 3)

In [22]:
# Матрица А размерности mxn
m = A.shape[0]
n = A.shape[1]
m, n

(2, 3)

In [26]:
# обращение к элементам с помощью циклов
for i in range(m):
    for j in range(n):
        print(A[i,j], end=' ')
    print()

1 2 3 
4 5 6 


In [27]:
# Кол-во элементов
A.size

6

In [28]:
len(mylist) # кол-во элементов списка

3

In [29]:
len(A) # кол-во элементов по первой оси (координате) = кол-во строк

2

In [30]:
# Получение типа массива
A.dtype

dtype('int64')

In [31]:
D = np.array([[1,2,3,4], [5, 6, 7, 8], [9, 10, 11, 12]])
D

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
len(D)

3

In [53]:
E = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
E

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
len(E) # кол-во эл-тов по 1-й координате

2

In [56]:
E.shape

(2, 2, 2)

In [60]:
# изменение формы массива
np.resize(E, (2, 10))

array([[1, 2, 3, 4, 5, 6, 7, 8, 1, 2],
       [3, 4, 5, 6, 7, 8, 1, 2, 3, 4]])

In [38]:
# задание нулевого массива
a = np.zeros(6)
a

array([0., 0., 0., 0., 0., 0.])

In [39]:
B = np.zeros((4,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
# Массив из единиц
C = np.ones((5,5))
C

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# Единичная матрица
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# Диагональная матрица
D = np.diag([1,2,3,4])
D

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [44]:
mlist = [1,2,3,4,5,6,7,8]
D = np.diag(mlist)
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

# Операции с массивами

In [48]:
A = np.ones((3,3))
B = np.ones((3,3))
B[1] = B[1] * 2 # Умножение на число
B[2] = B[2] * 3
A, B

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]]))

In [49]:
B = np.ones((3,3))
n = B.shape[1] # кол-во столбцов
for i in range(n):
    B[1, i] *=2
B

array([[1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [50]:
A + B # сложение массивов поэлементное

array([[2., 2., 2.],
       [3., 3., 3.],
       [2., 2., 2.]])

In [51]:
A * B # поэлементное умножение массивов

array([[1., 1., 1.],
       [2., 2., 2.],
       [1., 1., 1.]])

In [73]:
A = np.ones((3,3))
B = np.ones((3,3))
B[1] *= 2 # Умножение на число
A[2] *= 3
A, B

(array([[1., 1., 1.],
        [1., 1., 1.],
        [3., 3., 3.]]),
 array([[1., 1., 1.],
        [2., 2., 2.],
        [1., 1., 1.]]))

In [74]:
A / B # поэлементное деление массивов

array([[1. , 1. , 1. ],
       [0.5, 0.5, 0.5],
       [3. , 3. , 3. ]])

In [75]:
A**2 # Поэлементное возведениек в степень

array([[1., 1., 1.],
       [1., 1., 1.],
       [9., 9., 9.]])

In [5]:
A + 5 # допускается сложение массивов разной размерности!

array([[6., 6., 6.],
       [6., 6., 6.],
       [8., 8., 8.]])

In [21]:
D = np.ones(3)*7
D

array([7., 7., 7.])

In [22]:
D + A

array([[ 8.,  8.,  8.],
       [ 8.,  8.,  8.],
       [10., 10., 10.]])

In [34]:
A[1]+=1
A[2]*=3
A

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [36]:
# срезы
A[1:,1:]

array([[2., 2.],
       [3., 3.]])

# Векторные и матричные операции

In [38]:
a = np.array([1,2,3,4])
b = np.array([4,-2,1,3])
print(a, b)

[1 2 3 4] [ 4 -2  1  3]


In [39]:
# скалярное произведение одномерных массивов
np.dot(a, b)

15

In [40]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[1,2],[3, 4],[5,6]])
A, B

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2],
        [3, 4],
        [5, 6]]))

In [41]:
# матричное умножение 
np.dot(A, B)

array([[22, 28],
       [49, 64]])

In [42]:
np.dot(B, A)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [46]:
# Векторное произведение
a = np.array([1,1,1])
b = np.array([2,-2,2])
c = np.cross(a, b)
c

array([ 4,  0, -4])

## Найти площадь параллелограмма, построенного на векторах $a, b$?

In [52]:
S = np.sqrt(np.dot(c,c))
S

5.656854249492381

In [51]:
# И

2.0

In [61]:
F = np.array([[1,2,3], [4,5,6]])
F

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
np.resize(F, (3,4)) # НЕ ТРАНСПОНИРОВАНИЕ!!

array([[1, 2, 3, 4],
       [5, 6, 1, 2],
       [3, 4, 5, 6]])

In [63]:
# Транспонирование
np.transpose(F)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
F.reshape((3,2)) # Обратите внимание на отличие от resize

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
G = np.array([[1,2,3],[4,5,6],[7,8,9]])
G

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
G.diagonal()

array([1, 5, 9])

# Создание массивов из других массивов
### посмотреть в документации

In [76]:
G1 = G[0]
G2 = G[1:]
G1, G2

(array([1, 2, 3]),
 array([[4, 5, 6],
        [7, 8, 9]]))

In [79]:
# вертикальная склейка
np.vstack((G2,G1))

array([[4, 5, 6],
       [7, 8, 9],
       [1, 2, 3]])

In [81]:
# горизонтальная склейка
np.hstack((G1, G2[0]))

array([1, 2, 3, 4, 5, 6])

In [82]:
import scipy.linalg as la

In [83]:
la.det(G) # определитель

0.0

In [85]:
G

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [86]:
H = np.array([[1,0],[0,3]])
la.det(H)

3.0

In [88]:
# обратная матрица
H1 = la.inv(H)
H1

array([[ 1.        , -0.        ],
       [ 0.        ,  0.33333333]])

In [89]:
np.dot(H, H1)

array([[1., 0.],
       [0., 1.]])

# Решение СЛАУ
# $x_1 + x_2+ x_3= 6$
# $x_1 + x_2- x_3= 0$
# $2 x_1 + x_2+ x_3= 7$


In [91]:
A = np.array([[1,1,1],[1,1,-1],[2,1,1]]) # матрица системы
b = np.array([6,0,7])
A, b

(array([[ 1,  1,  1],
        [ 1,  1, -1],
        [ 2,  1,  1]]),
 array([6, 0, 7]))

In [92]:
x = la.solve(A, b)
x

array([1., 2., 3.])

# Как поменять строки матрицы местами?

In [93]:
def swap_rows(A, i, j):
    C = A[i]
    A[i] = A[j]
    A[j] = C

In [96]:
swap_rows(A, 0, 1)
A

array([[ 1,  1, -1],
       [ 1,  1, -1],
       [ 2,  1,  1]])

In [99]:
A[2]

array([2, 1, 1])

# ДЗ:
## 1. Исправить функцию перемены строк матрицы.
## 2. Написать функцию, которая реализует метод Гаусса.
## 3. Написать функцию, которая реализует метод прогонки для 3-х диагональных матриц (Thomas's Method) https://ru.wikipedia.org/wiki/Метод_прогонки
# https://en.wikipedia.org/wiki/Tridiagonal_matrix_algorithm .

In [3]:
'''
def swap_rows(A, i, j):
    for n in range(0, len(A)):
        A[i][n], A[j][n] = A[j][n], A[i][n]
'''

        
def swap_rows(A, i , j):
    tmp = A[i].copy()
    A[i] = A[j]
    A[j] = tmp

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [10]:
import numpy as np
import scipy.linalg as la

def gauss(a, b):
    for k in range(n):
        # Чтобы на диагонали всегда находились не "маленькие" числа
        if abs(a[k, k]) < 1.0e-12:
            for i in range(k + 1, n):
                if abs(a[i, k]) > abs(a[k, k]):                   # если следующией элемент больше предыдущего
                    for j in range(k, n):
                        a[k, j], a[i, j] = a[i, j],  a[k, j]      # то поменять строчки
                    b[k], b[i] = b[i], b[k]  
                    break
         
        pivot = a[k, k]  # опорный элемент
        for j in range(k, n):
            a[k, j] /= pivot
        b[k] /= pivot
    
        for i in range(n):
            if i == k or a[i, k] == 0: continue
            factor = a[i, k]
            for j in range(k, n):
                a[i, j] -= factor * a[k, j]
            b[i] -= factor * b[k]
            
    ###       
    # Обратный ход    
    # Сначала из последнего уравнения сразу находится значение последней переменной,
    # затем найденное значение подставляется в предпоследнее уравнение и находится
    # значение предпоследней переменной и т.д.
    ###
    
    for k in range(n - 1, -1, -1):
        b[k] = (b[k] - np.dot(a[k, k + 1 : n], b[k + 1 : n])) / a[k, k]
    
    return b, a

In [11]:
''' 
a = np.array([[1, 1, 1],
              [1, 1, -4],
              [2, 1, 1]])
              
a = np.array([[2, 1, 1],
              [2, 1, -4],
              [1, 2, 1]])
              
a = np.array([[2, -8, 0, 5], 
              [-9, 9, -7, 6], 
              [-6, 7, 3, 8], 
              [-1, 8, 5, 1]])
              
a = np.array([[2, -1, 0], 
              [-1, 2, -1], 
              [0, -1, 1]])
'''

a = np.array([[0., -1, 0], 
              [-1, 2, -1], 
              [0, -1, 1]])

#b = np.array([6, 0, 7])
#b = np.array([6, 12, 49, 34])

b = np.array([1, 0, 0])
n = len(b)
gauss(a, b)

(array([-1, -1, -1]),
 array([[ 1.,  0.,  0.],
        [ 0.,  1., -0.],
        [ 0.,  0.,  1.]]))

In [12]:
def Method_progon(A,b):
    n = A.shape[1]
    res = np.zeros(n)

    aa = np.zeros(n - 1)
    bb = np.zeros(n)

    aa[0] = A[0, 1] / A[0, 0]
    bb[0] = b[0] / A[0, 0]
    for i in range(1, n - 1):
        aa[i] = A[i, i + 1] / (A[i, i] - A[i, i - 1] * aa[i - 1])
        bb[i] = (b[i] - A[i, i - 1] * bb[i - 1]) / (A[i, i] - A[i, i - 1 ] * aa[i - 1])

        bb[n - 1] = (b[n - 1] - A[n - 1, n - 2] * bb[n - 2]) / (A[n - 1, n - 1] - A[n - 1, n - 2] * aa[n - 2])

    res[n - 1] = bb[n - 1]
    for i in range(n - 2, -1, -1 ):
        res[i] = bb[i] - aa[i] * res[i + 1]
    return res

In [15]:
print(Method_progon(a, b))
print(la.solve(a, b))

[-1. -1. -1.]
[-1. -1. -1.]
