In [1]:
import numpy as np
def GaussElim(A,b): # полагаем, что матрица А квадратная и невырожденная
    n = len(b)
    #x = np.zeros(n) # столбец решения
    # Elimination process
    for k in range(0, n - 1):
        for i in range(k + 1, n):
            if A[i, k] != 0.0:
                coeff = A[i, k] / A[k, k]
                A[i] -= coeff * A[k]
                # A[i, k + 1 : n] -= coeff * A[k, k + 1 : n]
                b[i] -= coeff * b[k]
                
    # Back substitution process
    
    for k in range(n - 1, -1, -1):
        #b[k] = (b[k] - np.dot(A[k], b)) / A[k, k]
        b[k] = (b[k] - np.dot(A[k, k + 1:n], b[k + 1:n])) / A[k, k]
    return A, b

In [2]:
def swap_rows(A, i , j):
    tmp = A[i].copy()
    A[i] = A[j]
    A[j] = tmp

In [2]:
A = np.array([[2, -8, 0,  5], [-9, 9, -7, 6],[-6, 7, 3, 8],[-1, 8, 5, 1]], dtype=float)
A

array([[ 2., -8.,  0.,  5.],
       [-9.,  9., -7.,  6.],
       [-6.,  7.,  3.,  8.],
       [-1.,  8.,  5.,  1.]])

In [21]:
swap_rows(A, 0 , 3)
A

array([[ 2., -8.,  0.,  5.],
       [-9.,  9., -7.,  6.],
       [-6.,  7.,  3.,  8.],
       [-1.,  8.,  5.,  1.]])

In [3]:
b = np.array([6, 12, 49, 34], dtype=float)
b

array([ 6., 12., 49., 34.])

In [5]:
GaussElim(A,b)[0]

array([[  2.        ,  -8.        ,   0.        ,   5.        ],
       [  0.        , -27.        ,  -7.        ,  28.5       ],
       [  0.        ,   0.        ,   7.40740741,   5.05555556],
       [  0.        ,   0.        ,   0.        ,   5.0175    ]])

In [6]:
A = np.array([[2, -1, 0], [-1, 2, -1],[0, -1, 1]], dtype=float)
b = np.array([1, 0, 0], dtype=float)
print(A, b)

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]] [1. 0. 0.]


In [7]:
GaussElim(A,b)

(array([[ 2.        , -1.        ,  0.        ],
        [ 0.        ,  1.5       , -1.        ],
        [ 0.        ,  0.        ,  0.33333333]]),
 array([1., 1., 1.]))

In [10]:
A = np.array([[2, -1, 0], [-1, 2, -1],[0, -1, 1]], dtype=float)
b = np.array([1, 0, 0], dtype=float)
swap_rows(A, 0, 1)
swap_rows(b, 0, 1)
print(A,b)

[[-1.  2. -1.]
 [ 2. -1.  0.]
 [ 0. -1.  1.]] [0. 1. 0.]


In [11]:
GaussElim(A,b)

(array([[-1.        ,  2.        , -1.        ],
        [ 0.        ,  3.        , -2.        ],
        [ 0.        ,  0.        ,  0.33333333]]),
 array([1., 1., 1.]))

In [16]:
swap_rows(A, 0, 2)
swap_rows(b, 0, 2)
print(A,b)

[[ nan  nan  nan]
 [ nan -inf  inf]
 [  0.  -1.   1.]] [nan nan nan]


In [12]:
A

array([[-1.        ,  2.        , -1.        ],
       [ 0.        ,  3.        , -2.        ],
       [ 0.        ,  0.        ,  0.33333333]])

In [23]:
A = np.array([[2, -1, 0], [-1, 2, -1],[0, -1, 1]], dtype=float)
b = np.array([1, 0, 0], dtype=float)

A[0] *= 1.e-36 # умножим на 10^{-4}
b[0] *= 1.e-36
GaussElim(A,b)

(array([[ 2.00000000e-36, -1.00000000e-36,  0.00000000e+00],
        [ 0.00000000e+00,  1.50000000e+00, -1.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  3.33333333e-01]]),
 array([1., 1., 1.]))

In [3]:
def GaussElimPivot(A,b, eps = 1.0e-10): # полагаем, что матрица А квадратная и невырожденная
    n = len(b)
    #x = np.zeros(n) # столбец решения
    
    # Elimination process
    for k in range(0, n - 1):
        if abs(A[k, k])< eps:
            swap_rows(A, A[k:,k].argmax(), k)
            swap_rows(b, A[k:,k].argmax(), k)
            
        for i in range(k + 1, n):
            if A[i, k] != 0.0:
                coeff = A[i, k] / A[k, k]
                A[i] -= coeff * A[k]
                # A[i, k + 1 : n] -= coeff * A[k, k + 1 : n]
                b[i] -= coeff * b[k]
                
    # Back substitution process
    
    for k in range(n - 1, -1, -1):
        #b[k] = (b[k] - np.dot(A[k], b)) / A[k, k]
        b[k] = (b[k] - np.dot(A[k, k + 1:n], b[k + 1:n])) / A[k, k]
    return A, b

In [26]:
b = np.array([1, 3, 6], dtype=float)
max(b) #  максимальный элемент

6.0

In [29]:
b.argmax() # индекс максимального элемента массива

2

In [15]:
A = np.array([[2, -8, 0,  5], [-9, 9, -7, 6],[-6, 7, 3, 8],[-1, 8, 5, 1]], dtype=float)
b = np.array([6, 12, 49, 34], dtype=float)
A, b

(array([[ 2., -8.,  0.,  5.],
        [-9.,  9., -7.,  6.],
        [-6.,  7.,  3.,  8.],
        [-1.,  8.,  5.,  1.]]),
 array([ 6., 12., 49., 34.]))

In [16]:
swap_rows(A, 0, 2)
swap_rows(b, 0, 2)

In [13]:
GaussElim(A,b)

<ipython-input-1-4c734cff26ed>:9: RuntimeWarning: divide by zero encountered in double_scalars
  coeff = A[i, k] / A[k, k]
<ipython-input-1-4c734cff26ed>:10: RuntimeWarning: invalid value encountered in multiply
  A[i] -= coeff * A[k]


(array([[  0.        ,   0.        ,   6.84126984,   3.95238095],
        [  0.        , -63.        , -52.        ,  -3.        ],
        [  0.        ,   0.        ,   0.        ,   4.65661253],
        [         nan,          nan,          nan,          nan]]),
 array([nan, nan, nan, nan]))

In [17]:
GaussElimPivot(A,b, eps = 1.0e-10)

(array([[ -6.        ,   7.        ,   3.        ,   8.        ],
        [  0.        ,  -1.5       , -11.5       ,  -6.        ],
        [  0.        ,   0.        ,  44.44444444,  30.33333333],
        [  0.        ,   0.        ,   0.        ,   5.0175    ]]),
 array([1., 2., 3., 4.]))

In [18]:
import scipy.linalg as la

In [19]:
help(la.solve_banded)

Help on function solve_banded in module scipy.linalg.basic:

solve_banded(l_and_u, ab, b, overwrite_ab=False, overwrite_b=False, debug=None, check_finite=True)
    Solve the equation a x = b for x, assuming a is banded matrix.
    
    The matrix a is stored in `ab` using the matrix diagonal ordered form::
    
        ab[u + i - j, j] == a[i,j]
    
    Example of `ab` (shape of a is (6,6), `u` =1, `l` =2)::
    
        *    a01  a12  a23  a34  a45
        a00  a11  a22  a33  a44  a55
        a10  a21  a32  a43  a54   *
        a20  a31  a42  a53   *    *
    
    Parameters
    ----------
    (l, u) : (integer, integer)
        Number of non-zero lower and upper diagonals
    ab : (`l` + `u` + 1, M) array_like
        Banded matrix
    b : (M,) or (M, K) array_like
        Right-hand side
    overwrite_ab : bool, optional
        Discard data in `ab` (may enhance performance)
    overwrite_b : bool, optional
        Discard data in `b` (may enhance performance)
    check_finite : bo

# Пример: Решить методом прогонки и с помощью функции solve_banded
# $-14x_1-6x_2=-78$
# $-9x_1+15x_2-x_3=-73$
# $x_2-11x_3+x_4=-38$
# $-7x_3+12x_4+3x_5=77$
# $ 6x_4-7x_5=91$

In [20]:
A = np.array([[-14, -6, 0, 0, 0],[-9, 15, -1, 0, 0],[0, 1, -11, 1, 0], 
              [0,  0, -7, 12, 3], [0, 0, 0, 6, -7]])
A

array([[-14,  -6,   0,   0,   0],
       [ -9,  15,  -1,   0,   0],
       [  0,   1, -11,   1,   0],
       [  0,   0,  -7,  12,   3],
       [  0,   0,   0,   6,  -7]])

In [21]:
b = np.array([-78, -73, -38, 77, 91])
b

array([-78, -73, -38,  77,  91])

In [38]:
u = np.hstack((np.zeros(1),A.diagonal(1)))
l = np.hstack((A.diagonal(-1), np.zeros(1)))
d = A.diagonal()
ab = np.vstack((u, d, l))
ab

array([[  0.,  -6.,  -1.,   1.,   3.],
       [-14.,  15., -11.,  12.,  -7.],
       [ -9.,   1.,  -7.,   6.,   0.]])

In [39]:
x = la.solve_banded((1,1), ab, b)
x

array([ 5.99374122, -0.98539618,  4.27538638, 10.0146464 , -4.41601737])

In [40]:
la.solve(A, b)

array([ 5.99374122, -0.98539618,  4.27538638, 10.0146464 , -4.41601737])

# ДЗ: 1. Проверить на различных вариантах раблтоспособность GaussElimPivot. Исправить воможные ошибки
# 2. Доделать реализацию метода прогонки и сравкнить решение с примером solve_banded
# 3. Написать функцию LU-разложения (LU decomposition) матрицы
# https://ru.wikipedia.org/wiki/LU-разложение
# https://en.wikipedia.org/wiki/LU_decomposition

In [20]:
# Lu-разложение 
import numpy as np

In [21]:

A = np.array([[-14, -6, 0, 0, 0],
              [-9, 15, -1, 0, 0],
              [0, 1, -11, 1, 0], 
              [0,  0, -7, 12, 3], 
              [0, 0, 0, 6, -7]])
b = np.array([[-78, -73, -38, 77, 91]])
n = len(A)
b.shape = (n, 1)

"""
A = np.array([[1, 0, 0], [330, 660, 0], [0, -330, 1165]])
b = np.array([[0, 5, 0]])"""

L, U = np.zeros((n, n)), np.zeros((n, n))

In [22]:
def LU(A, L, U, n):
    for i in range(n):
        U[i][i] = 1
        for j in range(i + 1):
            sigma = sum(L[i][k] * U[k][j] for k in range(j))
            L[i][j] = A[i][j] - sigma
        for j in range(i, n):
            sigma = sum(L[i][k] * U[k][j] for k in range(j))
            U[i][j] = (A[i][j] - sigma) / L[i][i]
    print('A =\n', A)
    #print(np.allclose(L @ U, A))
    #print(L @ U)
    
def backsub(b, L, U, n):
    x = b
    y = b
    for r in range(0, n):
        sigma = sum(L[r][c] * y[c] for c in range(0, r))
        y[r] = (b[r] - sigma) / L[r][r]
    
    x[n - 1] = y[n - 1] / U[n - 1][n - 1]
    
    for r in range(n - 2, -1, -1):
        sigma = sum(x[c] * U[r][c] for c in range(n - 1, r, -1))
        x[r] = (y[r] - sigma) / U[r][r]   
    print('x =', x)

LU(A, L, U, n)
backsub(b, L, U, n)

A =
 [[-14  -6   0   0   0]
 [ -9  15  -1   0   0]
 [  0   1 -11   1   0]
 [  0   0  -7  12   3]
 [  0   0   0   6  -7]]
x = [[ 5]
 [ 0]
 [ 3]
 [ 9]
 [-5]]


In [24]:
# LU-разложение (ленивый вариант)
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve

In [25]:
'''
*
*  A = P L U
*  P - матрица перестановок, 
*  L - нижнетреугольная матрица, 
*  U - верхнетреугольная матрица
*
'''

A = np.array([[-14, -6, 0, 0, 0],
              [-9, 15, -1, 0, 0],
              [0, 1, -11, 1, 0], 
              [0,  0, -7, 12, 3], 
              [0, 0, 0, 6, -7]])
b = np.array([[-78, -73, -38, 77, 91]])
b.shape = (5, 1)

# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu.html

P, L, U = lu(A)                              # compute pivoted LU decomposition of a matrix
np.allclose(A - P @ L @ U, np.zeros((5, 5)))
np.allclose(L @ U, A)

True

In [1]:
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_solve.html

LU, p = lu_factor(A)                         # compute pivoted LU decomposition of a matrix
lu_solve((LU, p), b)                         # solve an equation system using the LU factorization of a matrix

np.linalg.solve(A, b)

NameError: name 'lu_factor' is not defined

In [2]:
import numpy as np
import scipy.linalg as la